### ISSUE TITLE
Can't run webpack?

### ISSUE THREAD

**Issue by kamontat** [RachaneeSaeng/ReactTemplate#1]
I try to run webpack and npm start, but it's cause error to me.

<img width="243" alt="screen shot 2560-02-27 at 12 54 55 pm" src="https://cloud.githubusercontent.com/assets/14089557/23350285/1b296b1a-fcec-11e6-8135-6ace2033a894.png">

# Log File:
<code>
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webpack-server' ]
2 info using npm@3.10.9
3 info using node@v7.1.0
4 verbose run-script [ 'prewebpack-server', 'webpack-server', 'postwebpack-server' ]
5 info lifecycle react-template@1.0.0~prewebpack-server: react-template@1.0.0
6 silly lifecycle react-template@1.0.0~prewebpack-server: no script for prewebpack-server, continuing
7 info lifecycle react-template@1.0.0~webpack-server: react-template@1.0.0
8 verbose lifecycle react-template@1.0.0~webpack-server: unsafe-perm in lifecycle true
9 verbose lifecycle react-template@1.0.0~webpack-server: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/kamontat/Desktop/ReactTemplate-master/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/kamontat/Desktop/ReactTemplate-master/node_modules/.bin:/usr/local/Cellar/node/7.1.0/bin:/usr/local/git/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Users/kamontat/Framework/cocos2d-x-3.11/templates:/Users/kamontat/Framework:/Users/kamontat/Framework/cocos2d-x-3.11/tools/cocos2d-console/bin:/Users/kamontat/.rvm/gems/ruby-2.2.1/bin:/Users/kamontat/.rvm/gems/ruby-2.2.1@global/bin:/Users/kamontat/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kamontat/.rvm/bin
10 verbose lifecycle react-template@1.0.0~webpack-server: CWD: /Users/kamontat/Desktop/ReactTemplate-master
11 silly lifecycle react-template@1.0.0~webpack-server: Args: [ '-c', 'webpack-dev-server --hot --progress --colors' ]
12 silly lifecycle react-template@1.0.0~webpack-server: Returned: code: 1  signal: null
13 info lifecycle react-template@1.0.0~webpack-server: Failed to exec webpack-server script
14 verbose stack Error: react-template@1.0.0 webpack-server: `webpack-dev-server --hot --progress --colors`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-template@1.0.0
16 verbose cwd /Users/kamontat/Desktop/ReactTemplate-master
17 error Darwin 16.4.0
18 error argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "run" "webpack-server"
19 error node v7.1.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error react-template@1.0.0 webpack-server: `webpack-dev-server --hot --progress --colors`
22 error Exit status 1
23 error Failed at the react-template@1.0.0 webpack-server script 'webpack-dev-server --hot --progress --colors'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-template package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --hot --progress --colors
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-template
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-template
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
</code>

**Comment by RachaneeSaeng** [comment]
@kamontat 

Have you run command 'npm install' at the project location?
If yes, let's try to install typescript and webpack globally by command 
- npm install typescript -g
- npm install webpack -g
Then try again.

Cheer!
